### ISSUE TITLE
Volume owner and group related to the container user for rootless containers

### ISSUE THREAD

**Issue by sbancal** [linux-system-roles/podman#108]
For some containers to run, the volume is expected to be owned by a specific user, as defined by the container's author.
When running a rootless container, the owner and group seen on the host will be transposed according to the rule:

`uid_on_host = uid_in_container + subuid_range_start - 1`

For example, the `bitnami/openldap` container is expected to access to it's storage with the container's uid `1001`. The following task will fail because the folder will be seen as owned by `root` in the container.

```yml
- name: 'Define openldap kube container'
  ansible.builtin.include_role:
    name: linux-system-roles.podman
    apply:
      become: true
  vars:
    podman_create_host_directories: true
    podman_kube_specs:
      - state: started
        run_as_user: openldap
        run_as_group: openldap
        kube_file_content:
          apiVersion: v1
          kind: Pod
          metadata:
            name: openldap
          spec:
            containers:
              - name: openldap
                image: bitnami/openldap:2.6.6
                ports:
                  - containerPort: 389
                    hostPort: 1389
                  - containerPort: 636
                    hostPort: 1636
                volumeMounts:
                  - name: openldap-data
                    mountPath: /bitnami/openldap
            volumes:
              - name: openldap-data
                hostPath:
                  path: openldap_data
                  type: DirectoryOrCreate
```

When I add (297608 is the real uid/gid expected in this case):

```yml
    podman_host_directories:
      DEFAULT:
        owner: 297608
        group: 297608
        mode: "0644"
```

It will fail because there is no way, as non-root user, to `chown` to something other than it's own `uid`. And even if this works, it is not convenient as we have to calculate `owner` and `group` in a previous task.

A workaround, by the way, would be to run those 2 tasks just before:

```yml
- name: Create /opt/openldap/openldap_data directory
  become: true
  ansible.builtin.file:
    path: /opt/openldap/openldap_data
    owner: openldap
    group: openldap
    state: directory
    mode: '0750'

- name: Chown /opt/openldap/openldap_data
  become: true
  become_user: openldap
  ansible.builtin.command:
    cmd: podman unshare chown 1001.1001 /opt/openldap/openldap_data
```

But it would be really cool if `podman_host_directories` would do the `owner` and `group` transposition when running rootless (or provide new fields like `ctn_owner` and `ctn_group`).
