### ISSUE TITLE
Removing networks defined in quadlet does not work if they are named

### ISSUE THREAD

**Issue by Jakuje** [linux-system-roles/podman#150]
The quadlets support named networks with the `NetworkName` option:
```
$ cat quadlet/my-net.network 
[Network]
NetworkName=my-net
```
They are correctly created by this role:
```
        include_role:
          name: fedora.linux_system_roles.podman
        vars:
          podman_quadlet_specs:
            - file_src: quadlet/my-net.network
              state: started
```
(without the `systemd-` prefix):
```
podman network ls
NETWORK ID    NAME        DRIVER
9ece0594c97a  my-net    bridge
```
but removing them does not work:
```
        include_role:
          name: fedora.linux_system_roles.podman
        vars:
          podman_quadlet_specs:
            - file_src: quadlet/my-chess.network
              state: absent                                                                                          
```
It results in the following error:
```
fatal: [test]: FAILED! => {"changed": true, "cmd": ["podman", "network", "rm", "systemd-my-net"], "delta": "0:00:00.052382", "end": "2024-05-23 22:39:43.403237", "msg": "non-zero return code", "rc": 1, "start": "2024-05-23 22:39:43.350855", "stderr": "Error: unable to find network with name or ID systemd-my-net: network not found", "stderr_lines": ["Error: unable to find network with name or ID systemd-my-net: network not found"], "stdout": "", "stdout_lines": []}
```
