### ISSUE TITLE
podman_registries_conf TOML tables not supported

### ISSUE THREAD

**Issue by JoelKle** [linux-system-roles/podman#207]
## Summary

The `podman_registries_conf` configuration variable is missing support for TOML tables.
TOML tables are required to configure e.g. mirroring registries.

## Details

Example `registries.conf` with TOML tables for registry mirroring:
```
$ cat ~/.config/containers/registries.conf

[[registry]]
location="docker.io"
[[registry.mirror]]
location="jfrog.io"

[[registry]]
location="ghcr.io"
[[registry.mirror]]
location="jfrog.io"

[[registry]]
location="quay.io"
[[registry.mirror]]
location="jfrog.io"

[[registry]]
location="registry.access.redhat.com"
[[registry.mirror]]
location="jfrog.io"
```

I've found no way to use the `podman_registries_conf` conf variable to get the same result with the ansible role.
For me it looks like the `templates/toml.j2` template which is used to render the registries.conf has no support for TOML tables.

```
$ man containers-registries.conf
...
   NAMESPACED [[registry]] SETTINGS
       The  bulk  of  the  configuration is represented as an array of [[registry]] TOML tables; the settings may therefore differ among different registries as well as among different
       namespaces/repositories within a registry.
...
```

Blog post from RedHat:
https://www.redhat.com/en/blog/manage-container-registries

**Comment by baka-yuki** [comment]
does the following not work? you may need to do a yamllint rule to get it to be accepted but it should work from how the code looks.
```
podman_registries_conf:
  registry:
    location: "docker.io"
  registry.mirror:
    location: "jfrog.io"
  registry:
    location: "ghcr.io"
  registry.mirror:
    location: "jfrog.io"
  registry:
    location: "quay.io"
  registry.mirror:
    location: "jfrog.io"
  registry:
    location: "registry.access.redhat.com"
  registry.mirror:
    location: "jfrog.io"
```

**Comment by JoelKle** [comment]
@baka-yuki Unfortunately not. This YAML is invalid.
Each YAML key (`registry` and `registry.mirror`) has to be unique but here we have duplicated keys.

**Comment by baka-yuki** [comment]
ah you're right, it makes it through the parser but only the final key is actually saved. looking at the code again after sleep you're 100% correct the current implementation doesn't allow this. sorry about that!

**Comment by richm** [comment]
@JoelKle @baka-yuki if you can, please try https://github.com/linux-system-roles/podman/pull/218

**Comment by JoelKle** [comment]
@richm 
PR works for me. Thank you.
Tested with the following variables
```
podman_use_new_toml_formatter: true
podman_run_as_user: adm
podman_registries_conf:
  registry:
    - location: docker.io
      mirror:
        - location: jfrog.com
    - location: ghcr.io
      mirror:
        - location: jfrog.com
    - location: quay.io
      mirror:
        - location: jfrog.com
    - location: registry.access.redhat.com
      mirror:
        - location: jfrog.com
```
