### ISSUE TITLE
Directory .config/containers mode constantly changed

### ISSUE THREAD

**Issue by JoelKle** [linux-system-roles/podman#210]
I've use the podman role in user mode and set the following variables:

```yaml
podman_run_as_user: user

podman_storage_conf:
  storage:
    driver: overlay
    rootless_storage_path: /opt/user/podman/storage

podman_credential_files:
  - file_content: |
      {
        "auths": {
          "docker.xxx" : {
            "auth": "xxx"
          }
        }
      }

```

The task `Ensure storage.conf parent dir exists` in the `handle_storage_conf.yml` file sets the mode from the directory `~/.config/containers` to `0755`
See: https://github.com/linux-system-roles/podman/blob/main/tasks/handle_storage_conf.yml#L12

Later the directory mode is changed again to `0700` from the task `Ensure the credentials directory is present` in the file `handle_credential_files.yml`
See: https://github.com/linux-system-roles/podman/blob/main/tasks/handle_credential_files.yml#L51

I expect that there's the same problem in the `handle_policy_json.yml`
See: https://github.com/linux-system-roles/podman/blob/main/tasks/handle_policy_json.yml#L13

At the end we see constand changes in the directory mode:
```
TASK [fedora.linux_system_roles.podman : Ensure storage.conf parent dir exists] *************************************************************************************************************
changed: [xxx]
...
TASK [fedora.linux_system_roles.podman : Ensure the credentials directory is present] *******************************************************************************************************
changed: [xxx]
```
