### ISSUE TITLE
Trailing hyphen in running container name when name not defined in "spec" section

### ISSUE THREAD

**Issue by benblasco** [linux-system-roles/podman#35]
**Background**
The kube spec file allows us to name the pod and also name each individual container, e.g.
```
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-blueocean
spec:
  containers:
    - name: jenkins-blueocean
      image: docker.io/jenkinsci/blueocean:latest
...
```

**Problem:**
1. If we don't define a name in the metadata, the role fails.  Is this expected behaviour?
2. If we don't define a name for the container itself, the container name has a trailing hyphen like "jenkins-blueocean-", e.g.

kube spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-blueocean
spec:
  containers:
    - image: docker.io/jenkinsci/blueocean:latest
...
```

output:
```
[bblasco@nuc podman_container_yaml]$ podman ps -a
CONTAINER ID  IMAGE                                    COMMAND     CREATED        STATUS            PORTS                                              NAMES
1a4adda3dce2  localhost/podman-pause:4.3.1-1668180253              9 seconds ago  Up 7 seconds ago                                                     4c5bcc7196e2-service
a60edd6a9c9a  localhost/podman-pause:4.3.1-1668180253              9 seconds ago  Up 7 seconds ago  0.0.0.0:18080->8080/tcp, 0.0.0.0:50000->50000/tcp  df5b79203659-infra
18f068b93225  docker.io/jenkinsci/blueocean:latest                 6 seconds ago  Up 6 seconds ago  0.0.0.0:18080->8080/tcp, 0.0.0.0:50000->50000/tcp  jenkins-blueocean-
```

**Question**
What do we want the naming convention to be for the containers?  Is it valid to create the container without a name, and if so, should it have a trailing space?  In my opinion this looks wrong, so the solution is to either
a) Remove that trailing space
or
b) Force the user to name every container as well as the already mandatory pod name

Some guidance around sensible naming could be helpful here:

**Software versions**
Fedora 36
podman-4.3.1-1.fc36.x86_64

Ansible:
containers.podman         1.9.3  
fedora.linux_system_roles 1.31.3 

Please let me know if you need any more info.
