### ISSUE TITLE
podman secrets for rootless containers are created for root instead for the rootless user

### ISSUE THREAD

**Issue by jmberoud** [linux-system-roles/podman#90]
I'm using fedora.linux_system_roles 1.51.2
To recreate the issue:
```
- name: test
  hosts: localhost
  become: true
  become_user: root

  vars:
    podman_run_as_user: podman
    podman_run_as_group: podman
    podman_secrets: 
      - name: my-kube-password
        state: present
        skip_existing: true
        data: |
          apiVersion: v1
          data:
            password: dGVzdDEyMzQK
          kind: Secret
          metadata:
            name: my-kube-password
  roles:
    - fedora.linux_system_roles.podman
````
The secret is no created for the podman user:
```
(podman)$ podman secrets ls
ID          NAME        DRIVER      CREATED     UPDATED
````
but for the root user:
```
(root)# podman secrets ls
ID                         NAME              DRIVER      CREATED                 UPDATED
ffb146264f3b59908db45c99e  my-kube-password  file        Less than a second ago  Less than a second ago
````
When I modify handle_secrets.yml like this:
````
- name: Set variables part 1
  set_fact:
    __podman_user: "{{ __podman_quadlet_spec_item['run_as_user'] | d(podman_run_as_user) }}"

- name: Set variables part 2
  set_fact:
    __podman_rootless: "{{ __podman_user != 'root' }}"
    __podman_xdg_runtime_dir: >-
      /run/user/{{ ansible_facts["getent_passwd"][__podman_user][1] }}

- name: Manage each secret
  containers.podman.podman_secret:
    data: "{{ item.data | d(omit) }}"
    driver: "{{ item.driver | d(omit) }}"
    driver_opts: "{{ item.driver_opts | d(omit) }}"
    executable: "{{ item.executable | d(omit) }}"
    force: "{{ item.force | d(omit) }}"
    name: "{{ item.name }}"
    skip_existing: "{{ item.skip_existing | d(omit) }}"
    state: "{{ item.state | d(omit) }}"
  environment:
    XDG_RUNTIME_DIR: "{{ __podman_xdg_runtime_dir }}"
  become: "{{ __podman_rootless | ternary(true, omit) }}"
  become_user: "{{ __podman_rootless | ternary(__podman_user, omit) }}"
  no_log: true
  loop: "{{ podman_secrets }}"
````
Then it works as intended (secrets are available to the podman user)
